class MemoryError(Exception): ...


class BackendUnavailableError(MemoryError): ...


class QdrantUnavailableError(BackendUnavailableError): ...


class RedisUnavailableError(BackendUnavailableError): ...


class PostgresUnavailableError(BackendUnavailableError): ...
